In [1]:
import pandas as pd
import numpy as np
import os
main_dir=r"C:\Users\ffazzino\Downloads\Python_data_Wrangle\data"
data_dir=main_dir+r"\data"
os.chdir(data_dir)
print(os.getcwd())

C:\Users\ffazzino\Downloads\Python_data_Wrangle\data\data

In [2]:
noms=pd.read_excel('noms_excel.xlsx')
noms_codes=noms[['id_no','question_code','question_remarks','answer_value']]

In [11]:
noms.columns

Index(['id_no', 'icd10p', 'icd10s', 'icd10t', 'NOMS_Gend', 'declined_eth',
       'ethnicity', 'ethnic_detail', 'declined_race', 'AmerInd', 'AlasNa',
       'Asian', 'Black', 'HawPacif', 'White', 'dobmonth', 'dobyear',
       'sexual_orientation', 'Vital Date', 'is_current',
       'systolic_blood_pressure', 'diastolic_blood_pressure', 'weightkg',
       'heightcm', 'waistcircum_cm', 'NOMsdate', 'is_e_signed', 'event_name',
       'question_code', 'question_remarks', 'answer_value', 'program_name',
       'CCBHCmonth', 'CCBHCyear', 'CCBHC_start', 'CCBHC_end', 'event_log_id',
       'people_id'],
      dtype='object')

In [14]:
noms_codes.pivot(index='id_no',columns='question_code',values='answer_value')

question_code,A_OH,A_RM1,A_RM2,A_RM3,A_RM4,A_SO,B01,B02A,B02_1,B02_2,...,K_SS_02,K_SS_03,K_SS_04,K_SS_05,K_SS_06,K_SS_07,K_SS_08,K_SS_09,K_SS_10,K_SS_11
id_no,,,,,,,,,,,,,,,,,,,,,
00002742,No,[YES] [GO TO 2.],NaN,NaN,[CHILD],No,Good,NaN,Agree,Agree,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00002769,No,[YES] [GO TO 2.],NaN,NaN,[INDEPENDENT ADULT],No,Good,With support from others most of the time,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00003993,NaN,[NO] [GO TO 3.],NaN,[Consumer was not reached for interview],[GRANT STAFF],NaN,NaN,NaN,NaN,NaN,...,Yes,No,No,No,Yes,No,No,Yes,UNKNOWN,Yes
00004327,NaN,[NO] [GO TO 3.],NaN,[Consumer refused all interviews],[GRANT STAFF],NaN,NaN,NaN,NaN,NaN,...,Yes,No,No,No,No,Yes,No,No,No,No
00005165,No,[YES] [GO TO 2.],Jan 12 2022 12:00AM,NaN,[INDEPENDENT ADULT],No,Good,On my own some of the time and with support fr...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
W21489,No,[YES] [GO TO 2.],Jan 11 2022 12:00AM,NaN,[INDEPENDENT ADULT],No,Fair,On my own some of the time and with support fr...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
W24814,NaN,[YES] [GO TO 2.],Jan 14 2022 12:00AM,NaN,[INDEPENDENT ADULT],NaN,Good,On my own most of the time,NaN,NaN,...,Yes,No,No,No,No,No,No,No,No,No
W28203,NaN,[NO] [GO TO 3.],NaN,[Consumer was not reached for interview],[GRANT STAFF],NaN,Good,NaN,NaN,NaN,...,Yes,No,No,No,Yes,Yes,No,Yes,UNKNOWN,Yes
W30600,NaN,[NO] [GO TO 3.],NaN,[Consumer was not reached for interview],[GRANT STAFF],NaN,NaN,NaN,NaN,NaN,...,Yes,No,No,No,No,Yes,No,No,UNKNOWN,No
W35519,NaN,[NO] [GO TO 3.],NaN,[Consumer was not reached for interview],[GRANT STAFF],NaN,NaN,NaN,NaN,NaN,...,Yes,No,No,No,Yes,No,No,No,UNKNOWN,Yes

In [13]:
noms_codes.shape

(697, 4)

In [7]:
noms_demographics=noms[['id_no', 'icd10p', 'icd10s', 'icd10t', 'NOMS_Gend', 'declined_eth',
       'ethnicity', 'ethnic_detail', 'declined_race', 'AmerInd', 'AlasNa',
       'Asian', 'Black', 'HawPacif', 'White', 'dobmonth', 'dobyear',
       'sexual_orientation', 'Vital Date', 
       'systolic_blood_pressure', 'diastolic_blood_pressure', 'weightkg',
       'heightcm', 'waistcircum_cm', 'NOMsdate',  'event_name',
       'CCBHCmonth', 'CCBHCyear', 'CCBHC_start', 'CCBHC_end']]

In [8]:
noms_demographics

,id_no,icd10p,icd10s,icd10t,NOMS_Gend,declined_eth,ethnicity,ethnic_detail,declined_race,AmerInd,...,diastolic_blood_pressure,weightkg,heightcm,waistcircum_cm,NOMsdate,event_name,CCBHCmonth,CCBHCyear,CCBHC_start,CCBHC_end
0,00002742,F41.1,NaN,NaN,Male,False,Hispanic or Latino,Puerto Rican,False,NO,...,NaN,34.0,121.9,0,2022-01-11,*NOMs Child Baseline (WJCS),1,2022,2022-01-11,NaT
1,00002742,F41.1,NaN,NaN,Male,False,Hispanic or Latino,Puerto Rican,False,NO,...,NaN,34.0,121.9,0,2022-01-11,*NOMs Child Baseline (WJCS),1,2022,2022-01-11,NaT
2,00002742,F41.1,NaN,NaN,Male,False,Hispanic or Latino,Puerto Rican,False,NO,...,NaN,34.0,121.9,0,2022-01-11,*NOMs Child Baseline (WJCS),1,2022,2022-01-11,NaT
3,00002742,F41.1,NaN,NaN,Male,False,Hispanic or Latino,Puerto Rican,False,NO,...,NaN,34.0,121.9,0,2022-01-11,*NOMs Child Baseline (WJCS),1,2022,2022-01-11,NaT
4,00002742,F41.1,NaN,NaN,Male,False,Hispanic or Latino,Puerto Rican,False,NO,...,NaN,34.0,121.9,0,2022-01-11,*NOMs Child Baseline (WJCS),1,2022,2022-01-11,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692,W35519,F33.2,NaN,NaN,Female,False,Not Hispanic or Latino,NaN,False,NO,...,74.0,92.0,161.3,0,2022-01-10,*NOMs Child Reassessment (WJCS),7,2021,2021-07-13,NaT
693,W35519,F33.2,NaN,NaN,Female,False,Not Hispanic or Latino,NaN,False,NO,...,74.0,92.0,161.3,0,2022-01-10,*NOMs Child Reassessment (WJCS),7,2021,2021-07-13,NaT
694,W35519,F33.2,NaN,NaN,Female,False,Not Hispanic or Latino,NaN,False,NO,...,74.0,92.0,161.3,0,2022-01-10,*NOMs Child Reassessment (WJCS),7,2021,2021-07-13,NaT
695,W35519,F33.2,NaN,NaN,Female,False,Not Hispanic or Latino,NaN,False,NO,...,74.0,92.0,161.3,0,2022-01-10,*NOMs Child Reassessment (WJCS),7,2021,2021-07-13,NaT
696,W35519,F33.2,NaN,NaN,Female,False,Not Hispanic or Latino,NaN,False,NO,...,74.0,92.0,161.3,0,2022-01-10,*NOMs Child Reassessment (WJCS),7,2021,2021-07-13,NaT

In [9]:
noms_demographics.drop_duplicates()

,id_no,icd10p,icd10s,icd10t,NOMS_Gend,declined_eth,ethnicity,ethnic_detail,declined_race,AmerInd,...,diastolic_blood_pressure,weightkg,heightcm,waistcircum_cm,NOMsdate,event_name,CCBHCmonth,CCBHCyear,CCBHC_start,CCBHC_end
0,00002742,F41.1,NaN,NaN,Male,False,Hispanic or Latino,Puerto Rican,False,NO,...,NaN,34.0,121.9,0,2022-01-11,*NOMs Child Baseline (WJCS),1,2022,2022-01-11,NaT
70,00002769,F33.9,NaN,NaN,Female,False,Not Hispanic or Latino,NaN,False,NO,...,NaN,72.6,157.5,0,2022-01-10,*NOMs Adult Baseline (WJCS),1,2022,2022-01-10,NaT
142,00003993,F33.1,F10.10,NaN,Female,False,Hispanic or Latino,Puerto Rican,False,NO,...,NaN,92.5,165.1,0,2022-01-10,*NOMs Adult Reassessment (WJCS),7,2021,2021-07-12,NaT
211,00004327,F43.21,NaN,NaN,Male,False,Not Hispanic or Latino,NaN,False,NO,...,NaN,77.1,167.6,0,2022-01-11,*NOMs Adult Discharge (WJCS),8,2021,2021-08-12,2022-01-07
277,00005165,F43.21,NaN,NaN,Female,False,Not Hispanic or Latino,NaN,False,NO,...,NaN,95.3,165.1,0,2022-01-12,*NOMs Adult Baseline (WJCS),1,2022,2022-01-11,NaT
349,W21489,F31.0,F10.21,NaN,Female,False,Not Hispanic or Latino,NaN,False,NO,...,NaN,68.0,157.5,0,2022-01-11,*NOMs Adult Baseline (WJCS),1,2022,2022-01-11,NaT
422,W24814,F33.9,NaN,NaN,Female,False,Hispanic or Latino,Ecuadorian,False,YES,...,NaN,69.9,NaN,0,2022-01-14,*NOMs Adult Reassessment (WJCS),7,2021,2021-07-30,NaT
529,W28203,F25.0,Z79.899,NaN,Male,False,Not Hispanic or Latino,NaN,False,NO,...,NaN,90.7,182.9,0,2022-01-10,*NOMs Adult Reassessment (WJCS),7,2021,2021-07-08,NaT
596,W30600,F25.0,NaN,NaN,Male,False,Not Hispanic or Latino,NaN,False,NO,...,NaN,99.8,149.9,0,2022-01-14,*NOMs Adult Reassessment (WJCS),7,2021,2021-07-27,NaT
662,W35519,F33.2,NaN,NaN,Female,False,Not Hispanic or Latino,NaN,False,NO,...,74.0,92.0,161.3,0,2022-01-10,*NOMs Child Reassessment (WJCS),7,2021,2021-07-13,NaT